# Generated by Django 4.1.2 on 2022-12-07 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
